---
title: "HRV Variables"
author: "kittipos sirivongrungson"
date: '2022-04-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # Set WD to Root
here::i_am("dev/hrv-vars.Rmd")
library(here)
library(dplyr)
```


## Domain Variables

```{r HRV_vars_domain}
HRV_vars_domain <- list(time = c("SDNN", "SD_del_NN", "RMSSD", "Normals_count",
                                 "NN50_count", "NN50_percent"),
                        freq = c("Power_tot", "VLF_freq","VLF",
                                 "LF_freq","LF", "LF_nu",
                                 "HF_freq","HF", "HF_nu",
                                 "LF_HF")
)
```

```{r}
vars <- HRV_vars_domain

hrv_tbl %>% 
  select(Name, vars$freq)
```


## Variable Description

`HRV_vars_desc`: variable and description of HRV report.

```{r}
HRV_vars_desc
```


```{r HRV_vars_desc}
## HRV report variables description
HRV_vars_desc <- c(
  # Line 1
  File_LabChart = "LabChart file name",
  Channel = "Channel",
  Date = "Date",
  # Line 2
  Start_time = "Start time",
  End_time = "End time",
  # Line 3
  Name = "Name",
  Gender = "Gender",
  Age = "Age",
  # Line 4
  Beats_tot = "Total number of beats",
  Rec_length = "Length of recording (s)",
  # Line 5
  Class_bound = "Classification boundaries",
  # Line 6
  Discontinuities = "Discontinuities",
  Beats_inserted = "Manually inserted beats",
  Beats_deleted = "Manually deleted beats",
  # Line 7
  NN_max = "Maximum NN (ms)",
  NN_min = "Minimum NN (ms)",
  NN_range = "Range (Max - Min NN) (ms)",
  # Line 8
  NN_mean = "Mean NN (ms)",
  NN_median = "Median NN (ms)",
  HR_avg = "Average heart rate (BPM)",
  # Line 9
  SDNN = "SDNN (ms)",
  SD_del_NN = "SD of delta NN (ms)",
  RMSSD = "RMSSD",
  # Line 10
  Normals_count = "Normal beats count",
  Ectopics_count = "Ectopic beats count",
  Artifacts_count = "Artifacts count",
  NN50_count = "NN50 count",
  NN50_percent = "pNN50 (%)",
  # Line 11
  Spec_intv = "Spectrum intervals",
  Spec_mean_NN = "Mean spectrum NN (ms)",
  # Line 12
  Power_tot = "Total power (ms squared)",
  VLF_freq = "VLF frequency range (Hz)",
  VLF = "VLF (ms squared)",
  # Last Line
  LF_freq = "LF frequency range (Hz)",
  LF = "LF (ms squared)",
  LF_nu = "LF (nu)",

  HF_freq = "HF frequency range (Hz)",
  HF = "HF (ms squared)",
  HF_nu = "HF (nu)",

  LF_HF = "LF to HF ratio"
) %>%

  tibble::enframe("variable", "description")
```


